---
apiVersion: v1
kind: Pod
metadata:
  name: multi
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80
    - name: almalinux
      image: almalinux
      command: ["sleep","100"]
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule

